title: ARAAC
email: c.foale@federation.edu.au
description: >- # this means to ignore newlines until "baseurl:"
  Australian Responsible Autonomous Agents Collective
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

permalink: pretty

collections:
  researchers:
    output: true
  projects:
    output: true
  publications:
    output: true